# Generated by Django 3.2.7 on 2021-09-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0002_auto_20210917_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_name',
            field=models.CharField(blank=True, default='None', max_length=50),
        ),
    ]
